#ifndef MORIS_LINALG_HPP_
#define MORIS_LINALG_HPP_

// linalg header files.
#include "cl_Mat.hpp"
#include "cl_Sp_Mat.hpp"
#include "cl_Tensor.hpp"
#include "fn_chol_l.hpp"
#include "fn_chol_u.hpp"
#include "fn_cond.hpp"
#include "fn_ctrans.hpp"
#include "fn_det.hpp"
#include "fn_diag.hpp"
#include "fn_dot.hpp"
#include "fn_eig_gen.hpp"
#include "fn_eig_sym.hpp"
#include "fn_eye.hpp"
#include "fn_get_sparsity.hpp"
#include "fn_inv.hpp"
#include "fn_iscol.hpp"
#include "fn_isempty.hpp"
#include "fn_isfinite.hpp"
#include "fn_isrow.hpp"
#include "fn_issquare.hpp"
#include "fn_isvector.hpp"
#include "fn_linspace.hpp"
#include "fn_lu.hpp"
#include "fn_pinv.hpp"
#include "fn_qr.hpp"
#include "fn_sort.hpp"
#include "fn_svd.hpp"
#include "fn_mem_pointer.hpp"
#include "fn_trans.hpp"
#include "fn_prod.hpp"
#include "op_elemwise_div.hpp"
#include "op_elemwise_mult.hpp"
#include "op_equal_equal.hpp"
#include "op_greater.hpp"
#include "op_greater_equal.hpp"
#include "op_less.hpp"
#include "op_less_equal.hpp"
#include "op_minus.hpp"
#include "op_not_equal.hpp"
#include "op_ostream.hpp"
#include "op_plus.hpp"
#include "op_times.hpp"

#endif /* MORIS_LINALG_HPP_ */
