set( ${MORIS_PROJECT_NAME}_VERSION_RELEASE 0 )
set( ${MORIS_PROJECT_NAME}_VERSION_MAJOR "1" )
set( ${MORIS_PROJECT_NAME}_VERSION_MINOR "0" )
set( ${MORIS_PROJECT_NAME}_VERSION_MICRO "0" )

set( ${MORIS_PROJECT_NAME}_VERSION
    "${${MORIS_PROJECT_NAME}_VERSION_MAJOR}.${${MORIS_PROJECT_NAME}_VERSION_MINOR}.${${MORIS_PROJECT_NAME}_VERSION_MICRO}" )

if ( NOT ${MORIS_PROJECT_NAME}_VERSION_RELEASE )
    set( ${MORIS_PROJECT_NAME}_VERSION "${${MORIS_PROJECT_NAME}_VERSION}.dbg" )
endif()

# MESSAGE( STATUS ${${MORIS_PROJECT_NAME}_VERSION_MAJOR} )
# MESSAGE( STATUS ${${MORIS_PROJECT_NAME}_VERSION_MINOR} )
# MESSAGE( STATUS ${${MORIS_PROJECT_NAME}_VERSION_MICRO} )
# MESSAGE( STATUS ${${MORIS_PROJECT_NAME}_VERSION} )