%
% Copyright (c) 2022 University of Colorado
% Licensed under the MIT license. See LICENSE.txt file in the MORIS root for details.
%
%------------------------------------------------------------------------------------
%

function [Resvec,Jacmat] = ondim_tc_func(in1,in2,xA,xB,t1,t2,t1prev,t2prev,ctrho,ctvel,cttmp)
%ONDIM_TC_FUNC
%    [RESVEC,JACMAT] = ONDIM_TC_FUNC(IN1,IN2,XA,XB,T1,T2,T1PREV,T2PREV,CTRHO,CTVEL,CTTMP)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Jan-2021 21:00:20

rdof1 = in1(1,:);
rdof2 = in1(2,:);
rprev3 = in2(3,:);
rprev4 = in2(4,:);
tdof1 = in1(9,:);
tdof2 = in1(10,:);
tprev3 = in2(11,:);
tprev4 = in2(12,:);
vdof1 = in1(5,:);
vdof2 = in1(6,:);
vprev3 = in2(7,:);
vprev4 = in2(8,:);
Resvec = [ctrho.*(xA-xB).*(rdof1.*2.0+rdof2-rprev3.*2.0-rprev4).*(-1.0./6.0);ctrho.*(xA-xB).*(rdof1+rdof2.*2.0-rprev3-rprev4.*2.0).*(-1.0./6.0);0.0;0.0;ctvel.*(xA-xB).*(vdof1.*2.0+vdof2-vprev3.*2.0-vprev4).*(-1.0./6.0);ctvel.*(xA-xB).*(vdof1+vdof2.*2.0-vprev3-vprev4.*2.0).*(-1.0./6.0);0.0;0.0;cttmp.*(xA-xB).*(tdof1.*2.0+tdof2-tprev3.*2.0-tprev4).*(-1.0./6.0);cttmp.*(xA-xB).*(tdof1+tdof2.*2.0-tprev3-tprev4.*2.0).*(-1.0./6.0);0.0;0.0];
if nargout > 1
    Jacmat = reshape([ctrho.*(xA-xB).*(-1.0./3.0),ctrho.*(xA-xB).*(-1.0./6.0),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ctrho.*(xA-xB).*(-1.0./6.0),ctrho.*(xA-xB).*(-1.0./3.0),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ctvel.*(xA-xB).*(-1.0./3.0),ctvel.*(xA-xB).*(-1.0./6.0),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ctvel.*(xA-xB).*(-1.0./6.0),ctvel.*(xA-xB).*(-1.0./3.0),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,cttmp.*(xA-xB).*(-1.0./3.0),cttmp.*(xA-xB).*(-1.0./6.0),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,cttmp.*(xA-xB).*(-1.0./6.0),cttmp.*(xA-xB).*(-1.0./3.0),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[12,12]);
end

