    // 1D to 3D ---------------------------------------------------------------------------------------------------------------
    moris::Mat<moris::uint> tIndices1d3d(1,144);
    moris::Mat<moris::uint> tOffsets1d3d(1,51);

    // Edge 1
    tIndices1d3d(0,0)   = 9;    tIndices1d3d(0,1)   = 22;

    // Edge 2
    tIndices1d3d(0,2)   = 5 ;    tIndices1d3d(0,3)   = 21;

    // Edge 3
    tIndices1d3d(0,4)   = 1 ;    tIndices1d3d(0,5)   = 20;

    // Edge 4
    tIndices1d3d(0,6)   = 13;    tIndices1d3d(0,7)   = 23;

    // Edge 5
    tIndices1d3d(0,8)   = 11;    tIndices1d3d(0,9)   = 18;

    // Edge 6
    tIndices1d3d(0,10)  = 7 ;    tIndices1d3d(0,11)  = 17;

    // Edge 7
    tIndices1d3d(0,12)  = 3 ;    tIndices1d3d(0,13)  = 16;

    // Edge 8
    tIndices1d3d(0,14)  = 15;    tIndices1d3d(0,15)  = 19;

    // Edge 9
    tIndices1d3d(0,16)  = 10;    tIndices1d3d(0,17)  = 14;

    // Edge 10
    tIndices1d3d(0,18)  = 6 ;    tIndices1d3d(0,19)  = 8 ;

    // Edge 11
    tIndices1d3d(0,20)  = 0 ;    tIndices1d3d(0,21)  = 4 ;

    // Edge 12
    tIndices1d3d(0,22)  = 2 ;    tIndices1d3d(0,23)  = 12;

    // Edge 13
    tIndices1d3d(0,24)  = 1 ;    tIndices1d3d(0,25)  = 2 ;    tIndices1d3d(0,26)  = 12;
    tIndices1d3d(0,27)  = 13;    tIndices1d3d(0,28)  = 20;    tIndices1d3d(0,29)  = 23;

    // Edge 14
    tIndices1d3d(0,30)  = 2 ;    tIndices1d3d(0,31)  = 3 ;    tIndices1d3d(0,32)  = 12;
    tIndices1d3d(0,33)  = 15;    tIndices1d3d(0,34)  = 16;    tIndices1d3d(0,35)  = 19;

    // Edge 15
    tIndices1d3d(0,36)  = 0 ;    tIndices1d3d(0,37)  = 3 ;    tIndices1d3d(0,38)  = 4 ;
    tIndices1d3d(0,39)  = 7 ;    tIndices1d3d(0,40)  = 16;    tIndices1d3d(0,41)  = 17;

    // Edge 16
    tIndices1d3d(0,42)  = 0 ;    tIndices1d3d(0,43)  = 1 ;    tIndices1d3d(0,44)  = 4 ;
    tIndices1d3d(0,45)  = 5 ;    tIndices1d3d(0,46)  = 20;    tIndices1d3d(0,47)  = 21;

    // Edge 17
    tIndices1d3d(0,48)  = 6 ;    tIndices1d3d(0,49)  = 7 ;    tIndices1d3d(0,50)  = 8 ;
    tIndices1d3d(0,51)  = 11;    tIndices1d3d(0,52)  = 17;    tIndices1d3d(0,53)  = 18;

    // Edge 18
    tIndices1d3d(0,54)  = 5 ;    tIndices1d3d(0,55)  = 6 ;    tIndices1d3d(0,56)  = 8 ;
    tIndices1d3d(0,57)  = 9 ;    tIndices1d3d(0,58)  = 21;    tIndices1d3d(0,59)  = 22;

    // Edge 19
    tIndices1d3d(0,60)  = 9 ;    tIndices1d3d(0,61)  = 10;    tIndices1d3d(0,62)  = 13;
    tIndices1d3d(0,63)  = 14;    tIndices1d3d(0,64)  = 22;    tIndices1d3d(0,65)  = 23;

    // Edge 20
    tIndices1d3d(0,66)  = 10;    tIndices1d3d(0,67)  = 11;    tIndices1d3d(0,68)  = 14;
    tIndices1d3d(0,69)  = 15;    tIndices1d3d(0,70)  = 18;    tIndices1d3d(0,71)  = 19;

    // Edge 21
    tIndices1d3d(0,72)  = 1 ;    tIndices1d3d(0,73)  = 2 ;

    // Edge 22
    tIndices1d3d(0,74)  = 2 ;    tIndices1d3d(0,75)  = 3 ;

    // Edge 23
    tIndices1d3d(0,76)  = 0 ;    tIndices1d3d(0,77)  = 3 ;

    // Edge 24
    tIndices1d3d(0,78)  = 0 ;    tIndices1d3d(0,79)  = 1 ;

    // Edge 25
    tIndices1d3d(0,80)  = 4 ;    tIndices1d3d(0,81)  = 7 ;

    // Edge 26
    tIndices1d3d(0,82)  = 4 ;    tIndices1d3d(0,83)  = 5 ;

    // Edge 27
    tIndices1d3d(0,84)  = 5 ;    tIndices1d3d(0,85)  = 6 ;

    // Edge 28
    tIndices1d3d(0,86)  = 6 ;    tIndices1d3d(0,87)  = 7 ;

    // Edge 29
    tIndices1d3d(0,88)  = 10;    tIndices1d3d(0,89)  = 11;

    // Edge 30
    tIndices1d3d(0,90)  = 8 ;    tIndices1d3d(0,91)  = 11;

    // Edge 31
    tIndices1d3d(0,92)  = 8 ;    tIndices1d3d(0,93)  = 9 ;

    // Edge 32
    tIndices1d3d(0,94)  = 9 ;    tIndices1d3d(0,95)  = 10;

    // Edge 33
    tIndices1d3d(0,96)  = 12;    tIndices1d3d(0,97)  = 15;

    // Edge 34
    tIndices1d3d(0,98)  = 12;    tIndices1d3d(0,99)  = 13;

    // Edge 35
    tIndices1d3d(0,100) = 13;    tIndices1d3d(0,101) = 14;

    // Edge 36
    tIndices1d3d(0,102) = 14;    tIndices1d3d(0,103) = 15;

    // Edge 37
    tIndices1d3d(0,104) = 16;    tIndices1d3d(0,105) = 19;

    // Edge 38
    tIndices1d3d(0,106) = 16;    tIndices1d3d(0,107) = 17;

    // Edge 39
    tIndices1d3d(0,108) = 17;    tIndices1d3d(0,109) = 18;

    // Edge 40
    tIndices1d3d(0,110) = 18;    tIndices1d3d(0,111) = 19;

    // Edge 41
    tIndices1d3d(0,112) = 20;    tIndices1d3d(0,113) = 23;

    // Edge 42
    tIndices1d3d(0,114) = 20;    tIndices1d3d(0,115) = 21;

    // Edge 43
    tIndices1d3d(0,116) = 21;    tIndices1d3d(0,117) = 22;

    // Edge 44
    tIndices1d3d(0,118) = 22;    tIndices1d3d(0,119) = 23;

    // Edge 45
    tIndices1d3d(0,120) = 0 ;    tIndices1d3d(0,121) = 1 ;    tIndices1d3d(0,122) = 2 ;
    tIndices1d3d(0,123) = 3 ;

    // Edge 46
    tIndices1d3d(0,124) = 4 ;    tIndices1d3d(0,125) = 5 ;    tIndices1d3d(0,126) = 6 ;
    tIndices1d3d(0,127) = 7 ;

    // Edge 47
    tIndices1d3d(0,128) = 8 ;    tIndices1d3d(0,129) = 9 ;    tIndices1d3d(0,130) = 10;
    tIndices1d3d(0,131) = 11;

    // Edge 48
    tIndices1d3d(0,132) = 12;    tIndices1d3d(0,133) = 13;    tIndices1d3d(0,134) = 14;
    tIndices1d3d(0,135) = 15;

    // Edge 49
    tIndices1d3d(0,136) = 16;    tIndices1d3d(0,137) = 17;    tIndices1d3d(0,138) = 18;
    tIndices1d3d(0,139) = 19;

    // Edge 50
    tIndices1d3d(0,140) = 20;    tIndices1d3d(0,141) = 21;    tIndices1d3d(0,142) = 22;
    tIndices1d3d(0,143) = 23;

    //Offsets---------------------------------------------------------------------------

    tOffsets1d3d(0,0)  = 0  ;    tOffsets1d3d(0,1)  = 2  ;    tOffsets1d3d(0,2)  = 4  ;
    tOffsets1d3d(0,3)  = 6  ;    tOffsets1d3d(0,4)  = 8  ;    tOffsets1d3d(0,5)  = 10 ;
    tOffsets1d3d(0,6)  = 12 ;    tOffsets1d3d(0,7)  = 14 ;    tOffsets1d3d(0,8)  = 16 ;
    tOffsets1d3d(0,9)  = 18 ;    tOffsets1d3d(0,10) = 20 ;    tOffsets1d3d(0,11) = 22 ;
    tOffsets1d3d(0,12) = 24 ;    tOffsets1d3d(0,13) = 30 ;    tOffsets1d3d(0,14) = 36 ;
    tOffsets1d3d(0,15) = 42 ;    tOffsets1d3d(0,16) = 48 ;    tOffsets1d3d(0,17) = 54 ;
    tOffsets1d3d(0,18) = 60 ;    tOffsets1d3d(0,19) = 66 ;    tOffsets1d3d(0,20) = 72 ;
    tOffsets1d3d(0,21) = 74 ;    tOffsets1d3d(0,22) = 76 ;    tOffsets1d3d(0,23) = 78 ;
    tOffsets1d3d(0,24) = 80 ;    tOffsets1d3d(0,25) = 82 ;    tOffsets1d3d(0,26) = 84 ;
    tOffsets1d3d(0,27) = 86 ;    tOffsets1d3d(0,28) = 88 ;    tOffsets1d3d(0,29) = 90 ;
    tOffsets1d3d(0,30) = 92 ;    tOffsets1d3d(0,31) = 94 ;    tOffsets1d3d(0,32) = 96 ;
    tOffsets1d3d(0,33) = 98 ;    tOffsets1d3d(0,34) = 100;    tOffsets1d3d(0,35) = 102;
    tOffsets1d3d(0,36) = 104;    tOffsets1d3d(0,37) = 106;    tOffsets1d3d(0,38) = 108;
    tOffsets1d3d(0,39) = 110;    tOffsets1d3d(0,40) = 112;    tOffsets1d3d(0,41) = 114;
    tOffsets1d3d(0,42) = 116;    tOffsets1d3d(0,43) = 118;    tOffsets1d3d(0,44) = 120;
    tOffsets1d3d(0,45) = 124;    tOffsets1d3d(0,46) = 128;    tOffsets1d3d(0,47) = 132;
    tOffsets1d3d(0,48) = 136;    tOffsets1d3d(0,49) = 140;    tOffsets1d3d(0,50) = 144;
