    // 3D to 0D ---------------------------------------------------------------------------------------------------------------
    moris::Mat<moris::uint> tIndices3d0d(1,96);
    moris::Mat<moris::uint> tOffsets3d0d(1,25);

    tOffsets3d0d(0,0) = 0;

    // Subelement 1
    tIndices3d0d(0,0)  =  2;    tIndices3d0d(0,1) =  6;   tIndices3d0d(0,2) =   10;   tIndices3d0d(0,3)  = 14;
    tOffsets3d0d(0,1)  =  4;

    // Subelement 2
    tIndices3d0d(0,4)  =  2;    tIndices3d0d(0,5) =  3;   tIndices3d0d(0,6) =   10;   tIndices3d0d(0,7)  = 14;
    tOffsets3d0d(0,2)  =  8;

    // Subelement 3
    tIndices3d0d(0,8)  =  3;    tIndices3d0d(0,9) =  7;   tIndices3d0d(0,10) =  10;   tIndices3d0d(0,11) = 14;
    tOffsets3d0d(0,3)  =  12;

    // Subelement 4
    tIndices3d0d(0,12) =  6;    tIndices3d0d(0,13) = 7;    tIndices3d0d(0,14)  = 10;   tIndices3d0d(0,15) = 14;
    tOffsets3d0d(0,4)  = 16;

    // Subelement 5
    tIndices3d0d(0,16) =  2;    tIndices3d0d(0,17) = 6;    tIndices3d0d(0,18) = 9;   tIndices3d0d(0,19) = 14;
    tOffsets3d0d(0,5)  = 20;

    // Subelement 6
    tIndices3d0d(0,20) =  1;    tIndices3d0d(0,21) = 2;    tIndices3d0d(0,22) = 9;   tIndices3d0d(0,23) = 14;
    tOffsets3d0d(0,6)  = 24;

    // Subelement 7
    tIndices3d0d(0,24) =  1;    tIndices3d0d(0,25) = 5;    tIndices3d0d(0,26) = 9;   tIndices3d0d(0,27) = 14;
    tOffsets3d0d(0,7)  = 28;

    // Subelement 8
    tIndices3d0d(0,28) =  5;    tIndices3d0d(0,29) = 6;    tIndices3d0d(0,30) = 9;   tIndices3d0d(0,31) = 14;
    tOffsets3d0d(0,8) = 32;

    // Subelement 9
    tIndices3d0d(0,32) = 1;    tIndices3d0d(0,33) = 5;    tIndices3d0d(0,34) = 8;   tIndices3d0d(0,35) = 14;
    tOffsets3d0d(0,9) = 36;

    // Subelement 10
    tIndices3d0d(0,36) = 0;    tIndices3d0d(0,37) = 1;    tIndices3d0d(0,38) = 8;   tIndices3d0d(0,39) = 14;
    tOffsets3d0d(0,10) = 40;

    // Subelement 11
    tIndices3d0d(0,40) = 0;    tIndices3d0d(0,41) = 4;    tIndices3d0d(0,42) = 8;   tIndices3d0d(0,43) = 14;
    tOffsets3d0d(0,11) = 44;

    // Subelement 12
    tIndices3d0d(0,44) = 4;    tIndices3d0d(0,45) = 5;    tIndices3d0d(0,46) = 8;   tIndices3d0d(0,47) = 14;
    tOffsets3d0d(0,12) = 48;

    // Subelement 13
    tIndices3d0d(0,48) = 3;    tIndices3d0d(0,49) = 7;    tIndices3d0d(0,50) = 11;   tIndices3d0d(0,51) = 14;
    tOffsets3d0d(0,13) = 52;

    // Subelement 14
    tIndices3d0d(0,52) = 0;    tIndices3d0d(0,53) = 3;    tIndices3d0d(0,54) = 11;   tIndices3d0d(0,55) = 14;
    tOffsets3d0d(0,14) = 56;

    // Subelement 15
    tIndices3d0d(0,56) = 0;    tIndices3d0d(0,57) = 4;    tIndices3d0d(0,58) = 11;   tIndices3d0d(0,59) = 14;
    tOffsets3d0d(0,15) = 60;

    // Subelement 16
    tIndices3d0d(0,60) = 4;    tIndices3d0d(0,61) = 7;    tIndices3d0d(0,62) = 11;   tIndices3d0d(0,63) = 14;
    tOffsets3d0d(0,16) = 64;

    // Subelement 17
    tIndices3d0d(0,64) = 6;    tIndices3d0d(0,65) = 7;    tIndices3d0d(0,66) = 13;   tIndices3d0d(0,67) = 14;
    tOffsets3d0d(0,17) = 68;

    // Subelement 18
    tIndices3d0d(0,68) = 5;    tIndices3d0d(0,69) = 6;    tIndices3d0d(0,70) = 13;   tIndices3d0d(0,71) = 14;
    tOffsets3d0d(0,18) = 72;

    // Subelement 19
    tIndices3d0d(0,72) = 4;    tIndices3d0d(0,73) = 5;    tIndices3d0d(0,74) = 13;   tIndices3d0d(0,75) = 14;
    tOffsets3d0d(0,19) = 76;

    // Subelement 20
    tIndices3d0d(0,76) = 4;    tIndices3d0d(0,77) = 7;    tIndices3d0d(0,78) = 13;   tIndices3d0d(0,79) = 14;
    tOffsets3d0d(0,20) = 80;

    // Subelement 21
    tIndices3d0d(0,80) = 2;    tIndices3d0d(0,81) = 3;    tIndices3d0d(0,82) = 12;   tIndices3d0d(0,83) = 14;
    tOffsets3d0d(0,21) = 84;

    // Subelement 22
    tIndices3d0d(0,84) = 1;    tIndices3d0d(0,85) = 2;    tIndices3d0d(0,86) = 12;   tIndices3d0d(0,87) = 14;
    tOffsets3d0d(0,22) = 88;

    // Subelement 23
    tIndices3d0d(0,88) = 0;    tIndices3d0d(0,89) = 1;    tIndices3d0d(0,90) = 12;   tIndices3d0d(0,91) = 14;
    tOffsets3d0d(0,23) = 92;

    // Subelement 24
    tIndices3d0d(0,92) = 0;    tIndices3d0d(0,93) = 3;    tIndices3d0d(0,94) = 12;   tIndices3d0d(0,95) = 14;
    tOffsets3d0d(0,24) = 96;
