    // 2D to 0D ---------------------------------------------------------------------------------------------------------------
    moris::Mat<moris::uint> tIndices2d0d(1,180);
    moris::Mat<moris::uint> tOffsets2d0d(1,61);

    tIndices2d0d(0,0)   =  2 ;    tIndices2d0d(0,1)   =  6 ;    tIndices2d0d(0,2)   =  10; // Face 1
    tIndices2d0d(0,3)   =  2 ;    tIndices2d0d(0,4)   =  3 ;    tIndices2d0d(0,5)   =  10; // Face 2
    tIndices2d0d(0,6)   =  3 ;    tIndices2d0d(0,7)   =  7 ;    tIndices2d0d(0,8)   =  10; // Face 3
    tIndices2d0d(0,9)   =  6 ;    tIndices2d0d(0,10)  =  7 ;    tIndices2d0d(0,11)  =  10; // Face 4
    tIndices2d0d(0,12)  =  2 ;    tIndices2d0d(0,13)  =  6 ;    tIndices2d0d(0,14)  =  9 ; // Face 5
    tIndices2d0d(0,15)  =  1 ;    tIndices2d0d(0,16)  =  2 ;    tIndices2d0d(0,17)  =  9 ; // Face 6
    tIndices2d0d(0,18)  =  1 ;    tIndices2d0d(0,19)  =  5 ;    tIndices2d0d(0,20)  =  9 ; // Face 7
    tIndices2d0d(0,21)  =  5 ;    tIndices2d0d(0,22)  =  6 ;    tIndices2d0d(0,23)  =  9 ; // Face 8
    tIndices2d0d(0,24)  =  1 ;    tIndices2d0d(0,25)  =  5 ;    tIndices2d0d(0,26)  =  8 ; // Face 9
    tIndices2d0d(0,27)  =  0 ;    tIndices2d0d(0,28)  =  1 ;    tIndices2d0d(0,29)  =  8 ; // Face 10
    tIndices2d0d(0,30)  =  0 ;    tIndices2d0d(0,31)  =  4 ;    tIndices2d0d(0,32)  =  8 ; // Face 11
    tIndices2d0d(0,33)  =  4 ;    tIndices2d0d(0,34)  =  5 ;    tIndices2d0d(0,35)  =  8 ; // Face 12
    tIndices2d0d(0,36)  =  3 ;    tIndices2d0d(0,37)  =  7 ;    tIndices2d0d(0,38)  =  11; // Face 13
    tIndices2d0d(0,39)  =  0 ;    tIndices2d0d(0,40)  =  3 ;    tIndices2d0d(0,41)  =  11; // Face 14
    tIndices2d0d(0,42)  =  0 ;    tIndices2d0d(0,43)  =  4 ;    tIndices2d0d(0,44)  =  11; // Face 15
    tIndices2d0d(0,45)  =  4 ;    tIndices2d0d(0,46)  =  7 ;    tIndices2d0d(0,47)  =  11; // Face 16
    tIndices2d0d(0,48)  =  6 ;    tIndices2d0d(0,49)  =  7 ;    tIndices2d0d(0,50)  =  13; // Face 17
    tIndices2d0d(0,51)  =  5 ;    tIndices2d0d(0,52)  =  6 ;    tIndices2d0d(0,53)  =  13; // Face 18
    tIndices2d0d(0,54)  =  4 ;    tIndices2d0d(0,55)  =  5 ;    tIndices2d0d(0,56)  =  13; // Face 19
    tIndices2d0d(0,57)  =  4 ;    tIndices2d0d(0,58)  =  7 ;    tIndices2d0d(0,59)  =  13; // Face 20
    tIndices2d0d(0,60)  =  2 ;    tIndices2d0d(0,61)  =  3 ;    tIndices2d0d(0,62)  =  12; // Face 21
    tIndices2d0d(0,63)  =  1 ;    tIndices2d0d(0,64)  =  2 ;    tIndices2d0d(0,65)  =  12; // Face 22
    tIndices2d0d(0,66)  =  0 ;    tIndices2d0d(0,67)  =  1 ;    tIndices2d0d(0,68)  =  12; // Face 23
    tIndices2d0d(0,69)  =  0 ;    tIndices2d0d(0,70)  =  3 ;    tIndices2d0d(0,71)  =  12; // Face 24
    tIndices2d0d(0,72)  =  2 ;    tIndices2d0d(0,73)  =  10;    tIndices2d0d(0,74)  =  14; // Face 25
    tIndices2d0d(0,75)  =  3 ;    tIndices2d0d(0,76)  =  10;    tIndices2d0d(0,77)  =  14; // Face 26
    tIndices2d0d(0,78)  =  7 ;    tIndices2d0d(0,79)  =  10;    tIndices2d0d(0,80)  =  14; // Face 27
    tIndices2d0d(0,81)  =  6 ;    tIndices2d0d(0,82)  =  10;    tIndices2d0d(0,83)  =  14; // Face 28
    tIndices2d0d(0,84)  =  2 ;    tIndices2d0d(0,85)  =  9 ;    tIndices2d0d(0,86)  =  14; // Face 29
    tIndices2d0d(0,87)  =  1 ;    tIndices2d0d(0,88)  =  9 ;    tIndices2d0d(0,89)  =  14; // Face 30
    tIndices2d0d(0,90)  =  5 ;    tIndices2d0d(0,91)  =  9 ;    tIndices2d0d(0,92)  =  14; // Face 31
    tIndices2d0d(0,93)  =  6 ;    tIndices2d0d(0,94)  =  9 ;    tIndices2d0d(0,95)  =  14; // Face 32
    tIndices2d0d(0,96)  =  1 ;    tIndices2d0d(0,97)  =  8 ;    tIndices2d0d(0,98)  =  14; // Face 33
    tIndices2d0d(0,99)  =  0 ;    tIndices2d0d(0,100) =  8 ;    tIndices2d0d(0,101) =  14; // Face 34
    tIndices2d0d(0,102) =  4 ;    tIndices2d0d(0,103) =  8 ;    tIndices2d0d(0,104) =  14; // Face 35
    tIndices2d0d(0,105) =  5 ;    tIndices2d0d(0,106) =  8 ;    tIndices2d0d(0,107) =  14; // Face 36
    tIndices2d0d(0,108) =  3 ;    tIndices2d0d(0,109) =  11;    tIndices2d0d(0,110) =  14; // Face 37
    tIndices2d0d(0,111) =  0 ;    tIndices2d0d(0,112) =  11;    tIndices2d0d(0,113) =  14; // Face 38
    tIndices2d0d(0,114) =  4 ;    tIndices2d0d(0,115) =  11;    tIndices2d0d(0,116) =  14; // Face 39
    tIndices2d0d(0,117) =  7 ;    tIndices2d0d(0,118) =  11;    tIndices2d0d(0,119) =  14; // Face 40
    tIndices2d0d(0,120) =  6 ;    tIndices2d0d(0,121) =  13;    tIndices2d0d(0,122) =  14; // Face 41
    tIndices2d0d(0,123) =  5 ;    tIndices2d0d(0,124) =  13;    tIndices2d0d(0,125) =  14; // Face 42
    tIndices2d0d(0,126) =  4 ;    tIndices2d0d(0,127) =  13;    tIndices2d0d(0,128) =  14; // Face 43
    tIndices2d0d(0,129) =  7 ;    tIndices2d0d(0,130) =  13;    tIndices2d0d(0,131) =  14; // Face 44
    tIndices2d0d(0,132) =  2 ;    tIndices2d0d(0,133) =  12;    tIndices2d0d(0,134) =  14; // Face 45
    tIndices2d0d(0,135) =  1 ;    tIndices2d0d(0,136) =  12;    tIndices2d0d(0,137) =  14; // Face 46
    tIndices2d0d(0,138) =  0 ;    tIndices2d0d(0,139) =  12;    tIndices2d0d(0,140) =  14; // Face 47
    tIndices2d0d(0,141) =  3 ;    tIndices2d0d(0,142) =  12;    tIndices2d0d(0,143) =  14; // Face 48
    tIndices2d0d(0,144) =  2 ;    tIndices2d0d(0,145) =  6 ;    tIndices2d0d(0,146) =  14; // Face 49
    tIndices2d0d(0,147) =  2 ;    tIndices2d0d(0,148) =  3 ;    tIndices2d0d(0,149) =  14; // Face 50
    tIndices2d0d(0,150) =  3 ;    tIndices2d0d(0,151) =  7 ;    tIndices2d0d(0,152) =  14; // Face 51
    tIndices2d0d(0,153) =  6 ;    tIndices2d0d(0,154) =  7 ;    tIndices2d0d(0,155) =  14; // Face 52
    tIndices2d0d(0,156) =  1 ;    tIndices2d0d(0,157) =  2 ;    tIndices2d0d(0,158) =  14; // Face 53
    tIndices2d0d(0,159) =  1 ;    tIndices2d0d(0,160) =  5 ;    tIndices2d0d(0,161) =  14; // Face 54
    tIndices2d0d(0,162) =  5 ;    tIndices2d0d(0,163) =  6 ;    tIndices2d0d(0,164) =  14; // Face 55
    tIndices2d0d(0,165) =  0 ;    tIndices2d0d(0,166) =  1 ;    tIndices2d0d(0,167) =  14; // Face 56
    tIndices2d0d(0,168) =  0 ;    tIndices2d0d(0,169) =  4 ;    tIndices2d0d(0,170) =  14; // Face 57
    tIndices2d0d(0,171) =  4 ;    tIndices2d0d(0,172) =  5 ;    tIndices2d0d(0,173) =  14; // Face 58
    tIndices2d0d(0,174) =  0 ;    tIndices2d0d(0,175) =  3 ;    tIndices2d0d(0,176) =  14; // Face 59
    tIndices2d0d(0,177) =  4 ;    tIndices2d0d(0,178) =  7 ;    tIndices2d0d(0,179) =  14; // Face 60

    //Offsets
    tOffsets2d0d(0,0)  = 0  ;    tOffsets2d0d(0,1)  = 3  ;    tOffsets2d0d(0,2)  = 6  ;    tOffsets2d0d(0,3)  = 9  ;
    tOffsets2d0d(0,4)  = 12 ;    tOffsets2d0d(0,5)  = 15 ;    tOffsets2d0d(0,6)  = 18 ;    tOffsets2d0d(0,7)  = 21 ;
    tOffsets2d0d(0,8)  = 24 ;    tOffsets2d0d(0,9)  = 27 ;    tOffsets2d0d(0,10) = 30 ;    tOffsets2d0d(0,11) = 33 ;
    tOffsets2d0d(0,12) = 36 ;    tOffsets2d0d(0,13) = 39 ;    tOffsets2d0d(0,14) = 42 ;    tOffsets2d0d(0,15) = 45 ;
    tOffsets2d0d(0,16) = 48 ;    tOffsets2d0d(0,17) = 51 ;    tOffsets2d0d(0,18) = 54 ;    tOffsets2d0d(0,19) = 57 ;
    tOffsets2d0d(0,20) = 60 ;    tOffsets2d0d(0,21) = 63 ;    tOffsets2d0d(0,22) = 66 ;    tOffsets2d0d(0,23) = 69 ;
    tOffsets2d0d(0,24) = 72 ;    tOffsets2d0d(0,25) = 75 ;    tOffsets2d0d(0,26) = 78 ;    tOffsets2d0d(0,27) = 81 ;
    tOffsets2d0d(0,28) = 84 ;    tOffsets2d0d(0,29) = 87 ;    tOffsets2d0d(0,30) = 90 ;    tOffsets2d0d(0,31) = 93 ;
    tOffsets2d0d(0,32) = 96 ;    tOffsets2d0d(0,33) = 99 ;    tOffsets2d0d(0,34) = 102;    tOffsets2d0d(0,35) = 105;
    tOffsets2d0d(0,36) = 108;    tOffsets2d0d(0,37) = 111;    tOffsets2d0d(0,38) = 114;    tOffsets2d0d(0,39) = 117;
    tOffsets2d0d(0,40) = 120;    tOffsets2d0d(0,41) = 123;    tOffsets2d0d(0,42) = 126;    tOffsets2d0d(0,43) = 129;
    tOffsets2d0d(0,44) = 132;    tOffsets2d0d(0,45) = 135;    tOffsets2d0d(0,46) = 138;    tOffsets2d0d(0,47) = 141;
    tOffsets2d0d(0,48) = 144;    tOffsets2d0d(0,49) = 147;    tOffsets2d0d(0,50) = 150;    tOffsets2d0d(0,51) = 153;
    tOffsets2d0d(0,52) = 156;    tOffsets2d0d(0,53) = 159;    tOffsets2d0d(0,54) = 162;    tOffsets2d0d(0,55) = 165;
    tOffsets2d0d(0,56) = 168;    tOffsets2d0d(0,57) = 171;    tOffsets2d0d(0,58) = 174;    tOffsets2d0d(0,59) = 177;
    tOffsets2d0d(0,60) = 180;
