    // 2D to 1D ---------------------------------------------------------------------------------------------------------------
    moris::Mat<moris::uint> tIndices2d1d(1,180);
    moris::Mat<moris::uint> tOffsets2d1d(1,61);

    tIndices2d1d(0,0)   =  11 ;    tIndices2d1d(0,1)   =  23 ;    tIndices2d1d(0,2)   =  24 ; // Face 1
    tIndices2d1d(0,3)   =  3  ;    tIndices2d1d(0,4)   =  21 ;    tIndices2d1d(0,5)   =  24 ; // Face 2
    tIndices2d1d(0,6)   =  12 ;    tIndices2d1d(0,7)   =  21 ;    tIndices2d1d(0,8)   =  22 ; // Face 3
    tIndices2d1d(0,9)   =  7  ;    tIndices2d1d(0,10)  =  22 ;    tIndices2d1d(0,11)  =  23 ; // Face 4
    tIndices2d1d(0,12)  =  11 ;    tIndices2d1d(0,13)  =  25 ;    tIndices2d1d(0,14)  =  26 ; // Face 5
    tIndices2d1d(0,15)  =  2  ;    tIndices2d1d(0,16)  =  26 ;    tIndices2d1d(0,17)  =  27 ; // Face 6
    tIndices2d1d(0,18)  =  10 ;    tIndices2d1d(0,19)  =  27 ;    tIndices2d1d(0,20)  =  28 ; // Face 7
    tIndices2d1d(0,21)  =  6  ;    tIndices2d1d(0,22)  =  25 ;    tIndices2d1d(0,23)  =  28 ; // Face 8
    tIndices2d1d(0,24)  =  10 ;    tIndices2d1d(0,25)  =  30 ;    tIndices2d1d(0,26)  =  31 ; // Face 9
    tIndices2d1d(0,27)  =  1  ;    tIndices2d1d(0,28)  =  31 ;    tIndices2d1d(0,29)  =  32 ; // Face 10
    tIndices2d1d(0,30)  =  9  ;    tIndices2d1d(0,31)  =  29 ;    tIndices2d1d(0,32)  =  32 ; // Face 11
    tIndices2d1d(0,33)  =  5  ;    tIndices2d1d(0,34)  =  29 ;    tIndices2d1d(0,35)  =  30 ; // Face 12
    tIndices2d1d(0,36)  =  12 ;    tIndices2d1d(0,37)  =  33 ;    tIndices2d1d(0,38)  =  34 ; // Face 13
    tIndices2d1d(0,39)  =  4  ;    tIndices2d1d(0,40)  =  34 ;    tIndices2d1d(0,41)  =  35 ; // Face 14
    tIndices2d1d(0,42)  =  9  ;    tIndices2d1d(0,43)  =  35 ;    tIndices2d1d(0,44)  =  36 ; // Face 15
    tIndices2d1d(0,45)  =  8  ;    tIndices2d1d(0,46)  =  33 ;    tIndices2d1d(0,47)  =  36 ; // Face 16
    tIndices2d1d(0,48)  =  7  ;    tIndices2d1d(0,49)  =  37 ;    tIndices2d1d(0,50)  =  38 ; // Face 17
    tIndices2d1d(0,51)  =  6  ;    tIndices2d1d(0,52)  =  38 ;    tIndices2d1d(0,53)  =  39 ; // Face 18
    tIndices2d1d(0,54)  =  5  ;    tIndices2d1d(0,55)  =  39 ;    tIndices2d1d(0,56)  =  40 ; // Face 19
    tIndices2d1d(0,57)  =  8  ;    tIndices2d1d(0,58)  =  37 ;    tIndices2d1d(0,59)  =  40 ; // Face 20
    tIndices2d1d(0,60)  =  3  ;    tIndices2d1d(0,61)  =  41 ;    tIndices2d1d(0,62)  =  42 ; // Face 21
    tIndices2d1d(0,63)  =  2  ;    tIndices2d1d(0,64)  =  42 ;    tIndices2d1d(0,65)  =  43 ; // Face 22
    tIndices2d1d(0,66)  =  1  ;    tIndices2d1d(0,67)  =  43 ;    tIndices2d1d(0,68)  =  44 ; // Face 23
    tIndices2d1d(0,69)  =  4  ;    tIndices2d1d(0,70)  =  41 ;    tIndices2d1d(0,71)  =  44 ; // Face 24
    tIndices2d1d(0,72)  =  16 ;    tIndices2d1d(0,73)  =  24 ;    tIndices2d1d(0,74)  =  45 ; // Face 25
    tIndices2d1d(0,75)  =  13 ;    tIndices2d1d(0,76)  =  21 ;    tIndices2d1d(0,77)  =  45 ; // Face 26
    tIndices2d1d(0,78)  =  14 ;    tIndices2d1d(0,79)  =  22 ;    tIndices2d1d(0,80)  =  45 ; // Face 27
    tIndices2d1d(0,81)  =  15 ;    tIndices2d1d(0,82)  =  23 ;    tIndices2d1d(0,83)  =  45 ; // Face 28
    tIndices2d1d(0,84)  =  16 ;    tIndices2d1d(0,85)  =  26 ;    tIndices2d1d(0,86)  =  46 ; // Face 29
    tIndices2d1d(0,87)  =  18 ;    tIndices2d1d(0,88)  =  27 ;    tIndices2d1d(0,89)  =  46 ; // Face 30
    tIndices2d1d(0,90)  =  17 ;    tIndices2d1d(0,91)  =  28 ;    tIndices2d1d(0,92)  =  46 ; // Face 31
    tIndices2d1d(0,93)  =  15 ;    tIndices2d1d(0,94)  =  25 ;    tIndices2d1d(0,95)  =  46 ; // Face 32
    tIndices2d1d(0,96)  =  18 ;    tIndices2d1d(0,97)  =  31 ;    tIndices2d1d(0,98)  =  47 ; // Face 33
    tIndices2d1d(0,99)  =  19 ;    tIndices2d1d(0,100) =  32 ;    tIndices2d1d(0,101) =  47 ; // Face 34
    tIndices2d1d(0,102) =  20 ;    tIndices2d1d(0,103) =  29 ;    tIndices2d1d(0,104) =  47 ; // Face 35
    tIndices2d1d(0,105) =  17 ;    tIndices2d1d(0,106) =  30 ;    tIndices2d1d(0,107) =  47 ; // Face 36
    tIndices2d1d(0,108) =  13 ;    tIndices2d1d(0,109) =  34 ;    tIndices2d1d(0,110) =  48 ; // Face 37
    tIndices2d1d(0,111) =  19 ;    tIndices2d1d(0,112) =  35 ;    tIndices2d1d(0,113) =  48 ; // Face 38
    tIndices2d1d(0,114) =  20 ;    tIndices2d1d(0,115) =  36 ;    tIndices2d1d(0,116) =  48 ; // Face 39
    tIndices2d1d(0,117) =  14 ;    tIndices2d1d(0,118) =  33 ;    tIndices2d1d(0,119) =  48 ; // Face 40
    tIndices2d1d(0,120) =  15 ;    tIndices2d1d(0,121) =  38 ;    tIndices2d1d(0,122) =  49 ; // Face 41
    tIndices2d1d(0,123) =  17 ;    tIndices2d1d(0,124) =  39 ;    tIndices2d1d(0,125) =  49 ; // Face 42
    tIndices2d1d(0,126) =  20 ;    tIndices2d1d(0,127) =  40 ;    tIndices2d1d(0,128) =  49 ; // Face 43
    tIndices2d1d(0,129) =  14 ;    tIndices2d1d(0,130) =  37 ;    tIndices2d1d(0,131) =  49 ; // Face 44
    tIndices2d1d(0,132) =  16 ;    tIndices2d1d(0,133) =  42 ;    tIndices2d1d(0,134) =  50 ; // Face 45
    tIndices2d1d(0,135) =  18 ;    tIndices2d1d(0,136) =  43 ;    tIndices2d1d(0,137) =  50 ; // Face 46
    tIndices2d1d(0,138) =  19 ;    tIndices2d1d(0,139) =  44 ;    tIndices2d1d(0,140) =  50 ; // Face 47
    tIndices2d1d(0,141) =  13 ;    tIndices2d1d(0,142) =  41 ;    tIndices2d1d(0,143) =  50 ; // Face 48
    tIndices2d1d(0,144) =  11 ;    tIndices2d1d(0,145) =  15 ;    tIndices2d1d(0,146) =  16 ; // Face 49
    tIndices2d1d(0,147) =  3  ;    tIndices2d1d(0,148) =  13 ;    tIndices2d1d(0,149) =  16 ; // Face 50
    tIndices2d1d(0,150) =  12 ;    tIndices2d1d(0,151) =  13 ;    tIndices2d1d(0,152) =  14 ; // Face 51
    tIndices2d1d(0,153) =  7  ;    tIndices2d1d(0,154) =  14 ;    tIndices2d1d(0,155) =  15 ; // Face 52
    tIndices2d1d(0,156) =  2  ;    tIndices2d1d(0,157) =  16 ;    tIndices2d1d(0,158) =  18 ; // Face 53
    tIndices2d1d(0,159) =  10 ;    tIndices2d1d(0,160) =  17 ;    tIndices2d1d(0,161) =  18 ; // Face 54
    tIndices2d1d(0,162) =  6  ;    tIndices2d1d(0,163) =  15 ;    tIndices2d1d(0,164) =  17 ; // Face 55
    tIndices2d1d(0,165) =  1  ;    tIndices2d1d(0,166) =  18 ;    tIndices2d1d(0,167) =  19 ; // Face 56
    tIndices2d1d(0,168) =  9  ;    tIndices2d1d(0,169) =  19 ;    tIndices2d1d(0,170) =  20 ; // Face 57
    tIndices2d1d(0,171) =  5  ;    tIndices2d1d(0,172) =  17 ;    tIndices2d1d(0,173) =  20 ; // Face 58
    tIndices2d1d(0,174) =  4  ;    tIndices2d1d(0,175) =  13 ;    tIndices2d1d(0,176) =  19 ; // Face 59
    tIndices2d1d(0,177) =  8  ;    tIndices2d1d(0,178) =  14 ;    tIndices2d1d(0,179) =  20 ; // Face 60

    //Offsets
    tOffsets2d1d(0,0)  = 0  ;    tOffsets2d1d(0,1)  = 3  ;    tOffsets2d1d(0,2)  = 6  ;    tOffsets2d1d(0,3)  = 9  ;
    tOffsets2d1d(0,4)  = 12 ;    tOffsets2d1d(0,5)  = 15 ;    tOffsets2d1d(0,6)  = 18 ;    tOffsets2d1d(0,7)  = 21 ;
    tOffsets2d1d(0,8)  = 24 ;    tOffsets2d1d(0,9)  = 27 ;    tOffsets2d1d(0,10) = 30 ;    tOffsets2d1d(0,11) = 33 ;
    tOffsets2d1d(0,12) = 36 ;    tOffsets2d1d(0,13) = 39 ;    tOffsets2d1d(0,14) = 42 ;    tOffsets2d1d(0,15) = 45 ;
    tOffsets2d1d(0,16) = 48 ;    tOffsets2d1d(0,17) = 51 ;    tOffsets2d1d(0,18) = 54 ;    tOffsets2d1d(0,19) = 57 ;
    tOffsets2d1d(0,20) = 60 ;    tOffsets2d1d(0,21) = 63 ;    tOffsets2d1d(0,22) = 66 ;    tOffsets2d1d(0,23) = 69 ;
    tOffsets2d1d(0,24) = 72 ;    tOffsets2d1d(0,25) = 75 ;    tOffsets2d1d(0,26) = 78 ;    tOffsets2d1d(0,27) = 81 ;
    tOffsets2d1d(0,28) = 84 ;    tOffsets2d1d(0,29) = 87 ;    tOffsets2d1d(0,30) = 90 ;    tOffsets2d1d(0,31) = 93 ;
    tOffsets2d1d(0,32) = 96 ;    tOffsets2d1d(0,33) = 99 ;    tOffsets2d1d(0,34) = 102;    tOffsets2d1d(0,35) = 105;
    tOffsets2d1d(0,36) = 108;    tOffsets2d1d(0,37) = 111;    tOffsets2d1d(0,38) = 114;    tOffsets2d1d(0,39) = 117;
    tOffsets2d1d(0,40) = 120;    tOffsets2d1d(0,41) = 123;    tOffsets2d1d(0,42) = 126;    tOffsets2d1d(0,43) = 129;
    tOffsets2d1d(0,44) = 132;    tOffsets2d1d(0,45) = 135;    tOffsets2d1d(0,46) = 138;    tOffsets2d1d(0,47) = 141;
    tOffsets2d1d(0,48) = 144;    tOffsets2d1d(0,49) = 147;    tOffsets2d1d(0,50) = 150;    tOffsets2d1d(0,51) = 153;
    tOffsets2d1d(0,52) = 156;    tOffsets2d1d(0,53) = 159;    tOffsets2d1d(0,54) = 162;    tOffsets2d1d(0,55) = 165;
    tOffsets2d1d(0,56) = 168;    tOffsets2d1d(0,57) = 171;    tOffsets2d1d(0,58) = 174;    tOffsets2d1d(0,59) = 177;
    tOffsets2d1d(0,60) = 180;