
moris::Mat<moris::uint> tIndices0d1d = {{ 0, 2, 3, 1, 4, 0, 5, 1, 2, 3, 4, 5}};
moris::Mat<moris::uint> tIndices0d2d = {{ 0, 2, 3, 1, 0, 3, 1, 2, 3, 0, 1, 2}};
moris::Mat<moris::uint> tIndices0d3d = {{ 0, 0, 0, 0}};
moris::Mat<moris::uint> tIndices1d0d = {{ 0, 1, 1, 2, 0, 2, 0, 3, 1, 3, 2, 3}};
moris::Mat<moris::uint> tIndices1d2d = {{ 0, 3, 1, 3, 2, 3, 0, 2, 0, 1, 1, 2}};
moris::Mat<moris::uint> tIndices1d3d = {{ 0, 0, 0, 0, 0, 0}};
moris::Mat<moris::uint> tIndices2d0d = {{ 0, 1, 3, 1, 2, 3, 0, 2, 3, 0, 1, 2}};
moris::Mat<moris::uint> tIndices2d1d = {{ 0, 4, 3, 1, 5, 4, 2, 5, 3, 0, 1, 2}};
moris::Mat<moris::uint> tIndices2d3d = {{ 0, 0, 0, 0}};
moris::Mat<moris::uint> tIndices3d0d = {{ 0, 1, 2, 3}};
moris::Mat<moris::uint> tIndices3d1d = {{ 0, 1, 2, 3, 4, 5}};
moris::Mat<moris::uint> tIndices3d2d = {{ 0, 1, 2, 3}};

moris::Mat<moris::uint> tOffsets0d1d = {{0, 3, 6, 9, 12}};
moris::Mat<moris::uint> tOffsets0d2d = {{0, 3, 6, 9, 12}};
moris::Mat<moris::uint> tOffsets0d3d = {{0, 1, 2, 3, 4}};
moris::Mat<moris::uint> tOffsets1d0d = {{0, 2, 4, 6, 8, 10, 12}};
moris::Mat<moris::uint> tOffsets1d2d = {{0, 2, 4, 6, 8, 10, 12}};
moris::Mat<moris::uint> tOffsets1d3d = {{0, 1, 2, 3, 4, 5, 6}};
moris::Mat<moris::uint> tOffsets2d0d = {{0, 3, 6, 9, 12}};
moris::Mat<moris::uint> tOffsets2d1d = {{0, 3, 6, 9, 12}};
moris::Mat<moris::uint> tOffsets2d3d = {{0, 1, 2, 3, 4}};
moris::Mat<moris::uint> tOffsets3d0d = {{0, 4}};
moris::Mat<moris::uint> tOffsets3d1d = {{0, 6}};
moris::Mat<moris::uint> tOffsets3d2d = {{0, 4}};



